modLoader = "javafml"
loaderVersion = "[37,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "wands"
version = "${version}"
displayName = "Building Wands"
authors = "Me!"
description = '''
Building Wands!
'''
#logoFile = ""

[[dependencies.wands]]
modId = "forge"
mandatory = true
versionRange = "[37,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wands]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wands]]
modId = "architectury"
mandatory = true
versionRange = "[2.3.23,)"
ordering = "AFTER"
side = "BOTH"