modLoader = "javafml"
loaderVersion = "[39,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "wands"
version = "2.3.1"
displayName = "Building Wands"
authors = "nicguzzo"
description = '''
Building Wands!
'''
#logoFile = ""

[[dependencies.wands]]
modId = "forge"
mandatory = true
versionRange = "[39,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wands]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wands]]
modId = "architectury"
mandatory = true
versionRange = "[3.2,)"
ordering = "AFTER"
side = "BOTH"