modLoader = "javafml"
loaderVersion = "[42,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "wands"
version = "${version}"
displayName = "Building Wands"
authors = "nicguzzo"
description = '''
Building Wands!
'''
#logoFile = ""

[[dependencies.wands]]
modId = "forge"
mandatory = true
versionRange = "[42,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wands]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wands]]
modId = "architectury"
mandatory = true
versionRange = "[6.0.35 ,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.wands]]
modId = "cloth_config"
mandatory = true
ordering = "AFTER"
versionRange = "[8.0.75,)"

